apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "awx.postgres.pvName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "awx.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    {{- toYaml .Values.postgres.storage.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "awx.storageClassName" . }}
  hostPath:
    path: {{ .Values.postgres.storage.hostPath }}