apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "awx.storageClassName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "awx.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain