---
# Manage AWX Job Labels Task
# Creates and applies labels to AWX jobs based on the action being performed

- name: Determine action label based on cf_action
  set_fact:
    action_label: >-
      {%- if cf_action == 'create_record' -%}
        CREATE
      {%- elif cf_action == 'update_record' -%}
        UPDATE
      {%- elif cf_action == 'delete_record' -%}
        DELETE
      {%- elif cf_action == 'clone_record' -%}
        CLONE
      {%- elif cf_action == 'create_domain' -%}
        CREATE-DOMAIN
      {%- elif cf_action == 'update_settings' -%}
        UPDATE-SETTINGS
      {%- elif cf_action == 'sync' -%}
        SYNC
      {%- else -%}
        {{ cf_action | upper | default('UNKNOWN') }}
      {%- endif -%}

- name: Create action-specific label via API
  uri:
    url: "http://localhost:8052/api/v2/labels/"
    method: POST
    headers:
      Authorization: "Basic {{ (awx_username | default('admin') + ':' + awx_password) | b64encode }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ action_label }}"
      organization: 1
    return_content: true
    validate_certs: false
    status_code: [200, 201, 400]
  register: action_label_result
  ignore_errors: true

- name: Create record type label (if applicable)
  uri:
    url: "http://localhost:8052/api/v2/labels/"
    method: POST
    headers:
      Authorization: "Basic {{ (awx_username | default('admin') + ':' + awx_password) | b64encode }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ record_type | upper }}"
      organization: 1
    return_content: true
    validate_certs: false
    status_code: [200, 201, 400]
  register: type_label_result
  when: 
    - record_type is defined
    - cf_action in ['create_record', 'update_record', 'delete_record', 'clone_record']
  ignore_errors: true

- name: Create domain label
  uri:
    url: "http://localhost:8052/api/v2/labels/"
    method: POST
    headers:
      Authorization: "Basic {{ (awx_username | default('admin') + ':' + awx_password) | b64encode }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ resolved_domain | upper | replace('.', '-') }}"
      organization: 1
    return_content: true
    validate_certs: false
    status_code: [200, 201, 400]
  register: domain_label_result
  when: 
    - resolved_domain is defined
    - resolved_domain | length > 0
    - resolved_domain != 'undefined'
  ignore_errors: true

- name: Display label creation results
  debug:
    msg: "Labels applied: {{ action_label }}{{ ', ' + record_type | upper if record_type is defined and cf_action in ['create_record', 'update_record', 'delete_record', 'clone_record'] else '' }}{{ ', ' + resolved_domain | upper | replace('.', '-') if resolved_domain is defined and resolved_domain | length > 0 and resolved_domain != 'undefined' else '' }}"

- name: Apply labels to current job
  uri:
    url: "http://localhost:8052/api/v2/jobs/{{ tower_job_id }}/labels/"
    method: POST
    headers:
      Authorization: "Basic {{ (awx_username | default('admin') + ':' + awx_password) | b64encode }}"
      Content-Type: "application/json"
    body_format: json
    body:
      id: "{{ action_label_result.json.id }}"
    validate_certs: false
    status_code: [200, 201, 204, 400]
  register: job_label_apply_result
  when: 
    - tower_job_id is defined
    - action_label_result is defined
    - action_label_result.json is defined
    - action_label_result.json.id is defined
  ignore_errors: true

- name: Apply record type label to current job
  uri:
    url: "http://localhost:8052/api/v2/jobs/{{ tower_job_id }}/labels/"
    method: POST
    headers:
      Authorization: "Basic {{ (awx_username | default('admin') + ':' + awx_password) | b64encode }}"
      Content-Type: "application/json"
    body_format: json
    body:
      id: "{{ type_label_result.json.id }}"
    validate_certs: false
    status_code: [200, 201, 204, 400]
  register: job_type_label_apply_result
  when: 
    - tower_job_id is defined
    - type_label_result is defined
    - type_label_result.json is defined
    - type_label_result.json.id is defined
    - record_type is defined
    - cf_action in ['create_record', 'update_record', 'delete_record', 'clone_record']
  ignore_errors: true

- name: Apply domain label to current job
  uri:
    url: "http://localhost:8052/api/v2/jobs/{{ tower_job_id }}/labels/"
    method: POST
    headers:
      Authorization: "Basic {{ (awx_username | default('admin') + ':' + awx_password) | b64encode }}"
      Content-Type: "application/json"
    body_format: json
    body:
      id: "{{ domain_label_result.json.id }}"
    validate_certs: false
    status_code: [200, 201, 204, 400]
  register: job_domain_label_apply_result
  when: 
    - tower_job_id is defined
    - domain_label_result is defined
    - domain_label_result.json is defined
    - domain_label_result.json.id is defined
    - resolved_domain is defined
    - resolved_domain | length > 0
    - resolved_domain != 'undefined'
  ignore_errors: true