---
# Update Zone Level Settings (cache, SSL, security, performance)
# Required variables: zone_id, resolved_domain

- name: Build zone settings to update
  set_fact:
    settings_to_update: |
      {
        {% if cache_level is defined %}"cache_level": "{{ cache_level }}",{% endif %}
        {% if browser_cache_ttl is defined %}"browser_cache_ttl": {{ browser_cache_ttl }},{% endif %}
        {% if ssl_mode is defined %}"ssl": "{{ ssl_mode }}",{% endif %}
        {% if min_tls_version is defined %}"min_tls_version": "{{ min_tls_version }}",{% endif %}
        {% if always_use_https is defined %}"always_use_https": "{{ always_use_https }}",{% endif %}
        {% if automatic_https_rewrites is defined %}"automatic_https_rewrites": "{{ automatic_https_rewrites }}",{% endif %}
        {% if opportunistic_encryption is defined %}"opportunistic_encryption": "{{ opportunistic_encryption }}",{% endif %}
        {% if tls_1_3 is defined %}"tls_1_3": "{{ tls_1_3 }}",{% endif %}
        {% if http2 is defined %}"http2": "{{ http2 }}",{% endif %}
        {% if http3 is defined %}"http3": "{{ http3 }}",{% endif %}
        {% if websockets is defined %}"websockets": "{{ websockets }}",{% endif %}
        {% if ipv6 is defined %}"ipv6": "{{ ipv6 }}",{% endif %}
        {% if brotli is defined %}"brotli": "{{ brotli }}",{% endif %}
        {% if hotlink_protection is defined %}"hotlink_protection": "{{ hotlink_protection }}",{% endif %}
        {% if security_level is defined %}"security_level": "{{ security_level }}",{% endif %}
        {% if challenge_ttl is defined %}"challenge_ttl": {{ challenge_ttl }},{% endif %}
        {% if browser_check is defined %}"browser_check": "{{ browser_check }}",{% endif %}
        {% if development_mode is defined %}"development_mode": "{{ development_mode }}",{% endif %}
        {% if email_obfuscation is defined %}"email_obfuscation": "{{ email_obfuscation }}",{% endif %}
        {% if server_side_exclude is defined %}"server_side_exclude": "{{ server_side_exclude }}",{% endif %}
        {% if waf is defined %}"waf": "{{ waf }}",{% endif %}
        {% if rocket_loader is defined %}"rocket_loader": "{{ rocket_loader }}",{% endif %}
        {% if mirage is defined %}"mirage": "{{ mirage }}",{% endif %}
        {% if polish is defined %}"polish": "{{ polish }}",{% endif %}
        {% if webp is defined %}"webp": "{{ webp }}",{% endif %}
        {% if image_resizing is defined %}"image_resizing": "{{ image_resizing }}",{% endif %}
        {% if zero_rtt is defined %}"0rtt": "{{ zero_rtt }}",{% endif %}
        {% if early_hints is defined %}"early_hints": "{{ early_hints }}",{% endif %}
        "placeholder": "remove"
      }

- name: Clean settings object
  set_fact:
    clean_settings: "{{ settings_to_update | dict2items | rejectattr('key', 'equalto', 'placeholder') | list | items2dict }}"

- name: Update each zone setting
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/settings/{{ item.key }}"
    method: PATCH
    headers:
      Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
      Content-Type: "application/json"
    body_format: json
    body:
      value: "{{ item.value }}"
    return_content: true
    validate_certs: "{{ cf_validate_certs | default(true) }}"
  loop: "{{ clean_settings | dict2items }}"
  register: zone_settings_update_result
  ignore_errors: yes

- name: Track zone settings updates
  set_fact:
    global_changes: "{{ global_changes + [{'type': 'ZONE_SETTINGS_UPDATED', 'domain': resolved_domain, 'settings': clean_settings | dict2items | map(attribute='key') | list, 'updated_count': zone_settings_update_result.results | selectattr('json.success', 'defined') | selectattr('json.success', 'equalto', true) | list | length}] }}"
  when: zone_settings_update_result is defined

- name: Display result
  debug:
    msg:
      - "Zone settings updated for {{ resolved_domain }}"
      - "  Settings attempted: {{ clean_settings | dict2items | map(attribute='key') | list }}"
      - "  Successful: {{ zone_settings_update_result.results | selectattr('json.success', 'defined') | selectattr('json.success', 'equalto', true) | map(attribute='item.key') | list if zone_settings_update_result is defined else [] }}"
      - "  Failed: {{ zone_settings_update_result.results | selectattr('json.success', 'defined') | selectattr('json.success', 'equalto', false) | map(attribute='item.key') | list if zone_settings_update_result is defined else [] }}"
