---
# Manage DNS Records - Create/Update/Delete/Clone
# Required variables: zone_id, resolved_domain, fq_record_name, cf_action, record_type, record_value

- name: List all DNS records for this domain
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records"
    method: GET
    headers:
      Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
    return_content: true
    validate_certs: "{{ cf_validate_certs | default(true) }}"
  register: all_records_lookup
  when: zone_id is defined and zone_id | length > 0

- name: Ensure record_id has a default
  set_fact:
    record_id: "{{ record_id | default('') }}"

- name: Clone record
  when: cf_action == 'clone_record'
  block:
    - name: Get source domain zone ID
      uri:
        url: "https://api.cloudflare.com/client/v4/zones?name={{ source_domain | default(resolved_domain) }}"
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
        return_content: true
        validate_certs: "{{ cf_validate_certs | default(true) }}"
      register: source_zone_lookup

    - name: Set source zone_id
      set_fact:
        source_zone_id: "{{ source_zone_lookup.json.result[0].id if source_zone_lookup.json.result|length > 0 else '' }}"

    - name: Build source record name
      set_fact:
        source_fq_record_name: >-
          {%- if source_record_name is defined and source_record_name | length > 0 -%}
          {%- if source_record_name | regex_search('\.' ~ (source_domain | default(resolved_domain)) ~ '$') -%}
          {{ source_record_name | trim }}
          {%- elif source_record_name == '@' -%}
          {{ source_domain | default(resolved_domain) }}
          {%- else -%}
          {{ (source_record_name | trim) ~ '.' ~ (source_domain | default(resolved_domain)) }}
          {%- endif -%}
          {%- else -%}
          {{ resolved_record_name | default('') }}
          {%- endif -%}

    - name: Get source record details
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ source_zone_id }}/dns_records?type={{ record_type }}&name={{ source_fq_record_name | urlencode }}"
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
        return_content: true
        validate_certs: "{{ cf_validate_certs | default(true) }}"
      register: source_record_lookup
      when: source_zone_id is defined and source_zone_id | length > 0

    - name: Set source_record fact
      set_fact:
        source_record: "{{ source_record_lookup.json.result[0] if source_record_lookup.json.result|length > 0 else {} }}"
      when: source_record_lookup is defined

    - name: Build clone payload JSON
      set_fact:
        clone_payload_json: >-
          {{ ({'type': source_record.type | default(record_type),
               'name': fq_record_name,
               'content': (record_value | default(source_record.content | default(''))),
               'ttl': (record_ttl | default(source_record.ttl | default(3600)) | int),
               'priority': source_record.priority | default(omit) }
             ) | combine({'proxied': (record_proxied | default(source_record.proxied | default(false)) | bool) } if (source_record.type | default(record_type)) in ['A','AAAA','CNAME'] else {})
             | to_json }}
      when: source_record is defined and source_record | length > 0

    - name: Display clone details
      debug:
        msg:
          - "Cloning record from {{ source_domain | default(resolved_domain) }} to {{ resolved_domain }}"
          - "  Source: {{ source_fq_record_name }} ({{ source_record.type | default('N/A') }})"
          - "  Target: {{ fq_record_name }} ({{ source_record.type | default(record_type) }})"
          - "  Content: {{ source_record.content | default('N/A') }}"
          - "  TTL: {{ source_record.ttl | default(3600) }}"
          - "  Proxied: {{ source_record.proxied | default(false) }}"
      when: source_record is defined and source_record | length > 0

    - name: Write clone payload to temp file
      copy:
        content: "{{ clone_payload_json }}"
        dest: "/tmp/clone_payload_{{ inventory_hostname }}.json"
        mode: '0644'
      when: clone_payload_json is defined

    - name: Create cloned record
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ lookup('file', '/tmp/clone_payload_' ~ inventory_hostname ~ '.json') | from_json }}"
        return_content: true
        validate_certs: "{{ cf_validate_certs | default(true) }}"
      register: clone_result
      when: clone_payload_json is defined

    - name: Track clone result
      debug:
        msg: "[{{ 'SUCCESS' if (clone_result.json.success | default(false)) else 'FAILED' }}] Cloned {{ source_record.type | default(record_type) }} record: {{ source_fq_record_name }} → {{ fq_record_name }}"
      when: clone_result is defined

- name: Find existing record
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records?{% if record_type is defined %}type={{ record_type }}&{% endif %}name={{ fq_record_name | urlencode }}"
    method: GET
    headers:
      Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
    return_content: true
    validate_certs: "{{ cf_validate_certs | default(true) }}"
  register: record_lookup
  when: (record_id is not defined or record_id == '') and fq_record_name is defined and fq_record_name | length > 0

- name: Set record_id from lookup
  set_fact:
    record_id: "{{ record_lookup.json.result[0].id }}"
  when: record_lookup is defined and record_lookup.json is defined and record_lookup.json.result|length > 0

- name: Auto-convert create to update when record exists
  set_fact:
    cf_action: "update_record"
  when:
    - cf_action == 'create_record'
    - record_id is defined
    - record_id != ''

- name: Build record payload JSON
  set_fact:
    record_payload_json: >-
      {{ ({ 'type': record_type,
            'name': ((fq_record_name if (fq_record_name is defined and fq_record_name|length > 0) else effective_record_name) | trim),
            'content': (( '"' ~ (record_value|default('') | replace('"','') | trim) ~ '"') if record_type == 'TXT' else (record_value|default(''))),
            'ttl': (numeric_ttl|int if numeric_ttl is defined else 3600) }
         )
         | combine({'proxied': (effective_proxied | default(false))} if record_type in ['A','AAAA','CNAME'] else {})
         | combine({'priority': (record_priority|int if record_priority is defined else 10)} if record_type in ['MX','SRV'] else {})
         | to_json }}
  when: record_type is defined and cf_action in ['create_record','update_record']

- name: Write record payload to temp file
  copy:
    content: "{{ record_payload_json }}"
    dest: "/tmp/record_payload_{{ inventory_hostname }}.json"
    mode: '0644'
  when: cf_action in ['create_record','update_record']

- name: Validate CNAME target is not an IP address
  fail:
    msg: "CNAME record value looks like an IP ({{ record_value }}). CNAME must point to a hostname or FQDN. Use A/AAAA for IP addresses."
  when:
    - cf_action in ['create_record', 'update_record']
    - record_type is defined
    - record_type == 'CNAME'
    - record_value is defined
    - record_value is match('^\\d+\\.\\d+\\.\\d+\\.\\d+$')

- name: Validate CNAME target does not reference itself
  fail:
    msg: |
      CNAME content cannot reference itself.
      Record name: {{ fq_record_name }}
      CNAME target: {{ record_value }}
      
      A CNAME record cannot point to itself or create a circular reference.
      Please use a different target hostname.
  when:
    - cf_action in ['create_record', 'update_record']
    - record_type is defined
    - record_type == 'CNAME'
    - record_value is defined
    - fq_record_name is defined
    - (record_value | lower | trim | regex_replace('\\.$', '')) == (fq_record_name | lower | trim | regex_replace('\\.$', ''))

- name: Validate A record has valid IPv4 address
  fail:
    msg: |
      Content for A record must be a valid IPv4 address.
      Record type: A
      Content provided: {{ record_value }}
      
      A records must contain a valid IPv4 address (e.g., 203.0.113.10).
      If you want to point to a hostname, use a CNAME record instead.
  when:
    - cf_action in ['create_record', 'update_record']
    - record_type is defined
    - record_type == 'A'
    - record_value is defined
    - not (record_value | trim | regex_search('^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$'))

- name: Validate AAAA record has valid IPv6 address
  fail:
    msg: |
      Content for AAAA record must be a valid IPv6 address.
      Record type: AAAA
      Content provided: {{ record_value }}
      
      AAAA records must contain a valid IPv6 address (e.g., 2001:0db8::1).
      If you want to point to a hostname, use a CNAME record instead.
  when:
    - cf_action in ['create_record', 'update_record']
    - record_type is defined
    - record_type == 'AAAA'
    - record_value is defined
    - not (record_value | trim | regex_search('^[0-9a-fA-F:]+$'))

- name: Create or update record
  uri:
    url: >-
      https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records{{ '/' ~ (record_id | default('')) if (record_id | default('')) != '' and cf_action == 'update_record' else '' }}
    method: "{{ 'PUT' if cf_action == 'update_record' and (record_id | default('')) != '' else 'POST' }}"
    headers:
      Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ lookup('file', '/tmp/record_payload_' ~ inventory_hostname ~ '.json') | from_json }}"
    return_content: true
    validate_certs: "{{ cf_validate_certs | default(true) }}"
  when: cf_action in ['create_record','update_record']
  register: record_result
  ignore_errors: yes

- name: Fallback to curl if uri failed
  shell: >-
    curl -sS -X {{ 'PUT' if cf_action == 'update_record' and (record_id | default('')) != '' else 'POST' }} 
    "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records{{ '/' ~ (record_id | default('')) if (record_id | default('')) != '' and cf_action == 'update_record' else '' }}" \
      -H "Authorization: Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}" \
      -H 'Content-Type: application/json' \
      --data-binary @/tmp/record_payload_{{ inventory_hostname }}.json
  args:
    executable: /bin/bash
  when: cf_action in ['create_record','update_record'] and ((record_result is failed) or (record_result is defined and record_result.status is defined and record_result.status == -1))
  register: record_curl_result

- name: Normalize curl result
  set_fact:
    record_result: "{{ {'json': (record_curl_result.stdout | default('') | from_json) if record_curl_result.stdout|length > 0 else {} } }}"
  when: record_curl_result is defined and record_curl_result.stdout is defined

- name: Delete record
  when: cf_action == 'delete_record' and record_id
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records/{{ record_id }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ lookup('env','CLOUDFLARE_API_TOKEN') }}"
    return_content: true
    validate_certs: "{{ cf_validate_certs | default(true) }}"
  register: delete_result

- name: Display operation result
  debug:
    msg: >-
      {% if cf_action in ['create_record','update_record'] %}
      {% set success = (record_result.json.success if (record_result is defined and record_result.json is defined and record_result.json.success is defined) else false) %}
      {% if success %}[SUCCESS] {{ cf_action | replace('_', ' ') | title }}: {{ fq_record_name }} ({{ record_type }}){% else %}[FAILED] {{ cf_action | replace('_', ' ') | title }}: {{ fq_record_name }} - {{ (record_result.json.errors | map(attribute='message') | join(', ') if (record_result is defined and record_result.json is defined and record_result.json.errors is defined) else 'Unknown error') }}{% endif %}
      {% elif cf_action == 'delete_record' %}
      {% set success = (delete_result.json.success if (delete_result is defined and delete_result.json is defined and delete_result.json.success is defined) else false) %}
      {% if success %}[SUCCESS] Deleted: {{ fq_record_name }}{% if record_type is defined %} ({{ record_type }}){% endif %}{% else %}[FAILED] Delete failed: {{ fq_record_name }}{% endif %}
      {% endif %}

- name: Track domain level changes
  set_fact:
    domain_changes: "{{ domain_changes + [{'action': cf_action, 'record': fq_record_name, 'type': record_type | default('ANY'), 'status': 'success' if (record_result.json.success | default(false) or delete_result.json.success | default(false)) else 'failed'}] }}"
  when: cf_action in ['create_record','update_record','delete_record']
