---
# Deploy AWX Helm Chart Only
- hosts: localhost
  gather_facts: no
  vars:
    helm_charts_dir: helm-charts
  tasks:
    - name: Check if Kind cluster exists
      command: kind get clusters
      register: kind_clusters
      failed_when: false
      changed_when: false

    - name: Deploy AWX chart
      command: >
        helm upgrade --install awx
        {{ helm_charts_dir }}/charts/awx
        --namespace awx
        --create-namespace
        --values {{ helm_charts_dir }}/charts/awx/values.yaml
        --wait --timeout 15m
      register: awx_deploy

    - name: Display deployment results
      debug:
        msg: "AWX chart deployed successfully"
