---
# Remove Helm Charts
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Remove User Service
      command: helm uninstall user-service --namespace backend
      ignore_errors: yes

    - name: Remove Order Service
      command: helm uninstall order-service --namespace backend
      ignore_errors: yes

    - name: Remove PostgreSQL
      command: helm uninstall postgres --namespace database
      ignore_errors: yes

    - name: Remove Filebeat
      command: helm uninstall filebeat --namespace {{ namespace | default('default') }}
      ignore_errors: yes

    - name: Remove Logstash
      command: helm uninstall logstash --namespace {{ namespace | default('default') }}
      ignore_errors: yes

    - name: Remove Kibana
      command: helm uninstall kibana --namespace {{ namespace | default('default') }}
      ignore_errors: yes

    - name: Remove Elasticsearch
      command: helm uninstall elasticsearch --namespace {{ namespace | default('default') }}
      ignore_errors: yes

    - name: Remove AWX
      command: helm uninstall awx --namespace awx
      ignore_errors: yes

    - name: Remove AWX Operator
      command: helm uninstall awx-operator --namespace awx-system
      ignore_errors: yes

    - name: Remove MetalLB configuration
      command: helm uninstall metallb --namespace metallb-system
      ignore_errors: yes

    - name: Display removal results
      debug:
        msg: "All charts removed successfully"
