{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: database
  labels:
    app: postgres
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database.name }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.database.password }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        {{- if .Values.postgres.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "postgres.fullname" . }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
