---
# Enforce global record defaults (TTL, proxied) across all managed domains.
- name: Build global standardization targets
  set_fact:
    global_standardize_targets: "{{ lookup('template', 'automation/templates/cloudflare/global-targets.j2') | from_yaml | default([], true) }}"

- name: Report when no records require global standardization
  debug:
    msg: "No records require updates for global standardization."
  when: global_standardize_targets | length == 0

- name: Apply global standardization (per-target)
  include_tasks: apply-global-standardize-item.yml
  loop: "{{ global_standardize_targets }}"
  loop_control:
    loop_var: target
  when:
    - global_standardize_targets | length > 0
    - (dry_run | default(true) | bool) == false
