---
# Minimal, well-formed manage-record tasks file for AWX include parsing

- name: "Sanity: set a few simple facts"
  set_fact:
    effective_record_full_name: "Test-awx.efutechnologies.co.za"
    effective_record_type: "CNAME"
    effective_record_content: "example.com"

- name: "Sanity: show the simple facts"
  debug:
    msg:
      - "record_name={{ effective_record_full_name }}"
      - "record_type={{ effective_record_type }}"
      - "record_value={{ effective_record_content }}"

