---
# Clone standard records across domains ensuring consistent configuration.

- name: Ensure safe vars for record keys and presets
  set_fact:
    record_keys_safe: "{{ record_keys | default([]) }}"
    standard_records_safe: "{{ standard_records | default({}) }}"
    platform_presets_safe: "{{ platform_presets | default({}) }}"

- name: Determine selected record keys for platform sync
  set_fact:
    selected_record_keys: >-
      {{
        (record_keys_safe
         if (record_keys_safe | length) > 0
         else (
           (platform_presets_safe.get(platform_preset, {}).get('record_keys', []))
           if (platform_preset is defined and (platform_presets_safe | length) > 0)
           else ((standard_records_safe.keys() | list) if (standard_records_safe | length) > 0 else [])
         )
        )
      }}

- name: Ensure record keys exist in standard profile
  assert:
    that:
      - (selected_record_keys | difference(standard_records_safe.keys() | list)) | length == 0
    fail_msg: >-
      Some record keys are not defined in standard_records: {{ selected_record_keys | difference(standard_records_safe.keys() | list) }}

- name: Build platform synchronization targets
  set_fact:
    platform_sync_targets: "{{ lookup('first_found', {'files': ['automation/templates/cloudflare/platform-targets.j2','templates/cloudflare/platform-targets.j2'], 'errors': 'ignore'}) | from_yaml | default([], true) }}"

- name: Collect errors from target generation
  set_fact:
    platform_sync_errors: "{{ platform_sync_targets | selectattr('error', 'defined') | list }}"

- name: Fail if platform sync target generation detected issues
  assert:
    that:
      - platform_sync_errors | length == 0
    fail_msg: >-
      Platform sync preparation failed: {{ platform_sync_errors }}

- name: Filter valid targets
  set_fact:
    platform_sync_valid_targets: "{{ platform_sync_targets | rejectattr('error', 'defined') | list }}"

- name: Report when no targets require synchronization
  debug:
    msg: "No records require synchronization across domains."
  when: platform_sync_valid_targets | length == 0

- name: Apply platform synchronization (per-target)
  include_tasks: apply-platform-sync-item.yml
  loop: "{{ platform_sync_valid_targets }}"
  loop_control:
    loop_var: target
  when: platform_sync_valid_targets | length > 0
