{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-kibana-config
  namespace: monitoring
  labels:
    app: kibana
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: {{ .Values.kibana.elasticsearch.hosts | toJson }}
    
    # Disable security completely (no enrollment token required)
    xpack.security.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"
    
    # Logging configuration
    logging.root.level: info
{{- end }}