apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-awx-proxy-conf
  namespace: awx
data:
  default.conf: |
    server {
      listen 443 ssl;
      server_name 127.0.0.1;

      ssl_certificate /etc/nginx/tls/tls.crt;
      ssl_certificate_key /etc/nginx/tls/tls.key;
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers HIGH:!aNULL:!MD5;

      location / {
        proxy_pass http://ansible-awx-service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-awx-proxy
  namespace: awx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-awx-proxy
  template:
    metadata:
      labels:
        app: nginx-awx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.24-alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: tls
          mountPath: /etc/nginx/tls
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-awx-proxy-conf
          items:
            - key: default.conf
              path: default.conf
      - name: tls
        secret:
          secretName: nginx-awx-tls

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-awx-proxy
  namespace: awx
spec:
  selector:
    app: nginx-awx-proxy
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
