---
- name: Cloudflare API connectivity test
  hosts: localhost
  gather_facts: false
  vars:
    cloudflare_api_token: "{{ lookup('env','CLOUDFLARE_API_TOKEN') | default('') | trim }}"

  tasks:
    - name: Show token summary
      debug:
        msg: "token={{ cloudflare_api_token | default('') | regex_replace('.{4}$','****') }}"

    - name: Validate token present
      fail:
        msg: "CLOUDFLARE_API_TOKEN is required for this test"
      when: cloudflare_api_token == ''

    - name: Fetch zones from Cloudflare
      uri:
        validate_certs: false
        url: "https://api.cloudflare.com/client/v4/zones?per_page=50"
        method: GET
        headers:
          Authorization: "Bearer {{ cloudflare_api_token }}"
          Content-Type: "application/json"
        return_content: true
      register: zones_response

    - name: Dump zones_response summary
      debug:
        msg: |
          {% if zones_response is defined and zones_response.json is defined %}
          status={{ zones_response.status | default('n/a') }}
          success={{ zones_response.json.success | default('n/a') }}
          zones_count={{ (zones_response.json.result | default([])) | length }}
          {% else %}
          zones_response not defined (likely running in --check)
          {% endif %}

    - name: Show first 10 zone names
      debug:
        msg: "{{ (zones_response.json.result | default([]) | map(attribute='name') | list)[:10] }}"
      when: zones_response.json.success is defined and zones_response.json.success
