---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Map survey variables -> playbook variables
      set_fact:
        domain: "{{ survey_domain | default(domain | default('')) }}"
        action: "{{ survey_action | default(action | default('')) }}"

    - include_tasks: ../../tasks/cloudflare/global-standardize.yml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: ../../tasks/cloudflare/global-standardize.yml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: ../../tasks/cloudflare/global-standardize.yml
