---
- name: Debug wrapper to keep runner alive
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Snapshot runner inventory to /tmp for inspection (Ansible copy)
      block:
        - name: Determine AWX private data dir from env
          set_fact:
            awx_pdd: "{{ lookup('env','AWX_PRIVATE_DATA_DIR') | default('') }}"

        - name: Snapshot inventory file if present
          copy:
            src: "{{ awx_pdd }}/inventory/hosts"
            dest: /tmp/awx_inventory_snapshot.json
            remote_src: yes
          when: awx_pdd != ''
      rescue:
        - debug:
            msg: "Could not snapshot inventory (it may not exist yet)"
      always:
        - debug:
            msg: "Snapshot step finished"

    - name: Pause for debugging
      pause:
        seconds: 600

    - name: Include original wrapper
      import_playbook: wrapper-manage-record.yml
