---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Map survey variables -> playbook variables
      set_fact:
        domain: "{{ survey_domain | default(domain | default('')) }}"
        cf_action: "{{ survey_action | default(cf_action | default('')) }}"

    - include_tasks: ../../tasks/cloudflare/sync-governance-template.yml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: ../../tasks/cloudflare/sync-governance-template.yml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: ../../tasks/cloudflare/sync-governance-template.yml
