{{- if .Values.userService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: backend
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.userService.application.database.password | quote }}
{{- end }}
