{{- if .Values.filebeat.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-filebeat
  namespace: monitoring
  labels:
    app: filebeat
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: filebeat
      {{- include "elk-stack-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: filebeat
        {{- include "elk-stack-platform.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "elk-stack-platform.fullname" . }}-filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: {{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e"
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ .Values.filebeat.elasticsearchHost }}
        - name: ELASTICSEARCH_PORT
          value: {{ .Values.filebeat.elasticsearchPort | quote }}
        - name: LOGSTASH_HOST
          value: {{ .Values.filebeat.logstashHost }}
        - name: LOGSTASH_PORT
          value: {{ .Values.filebeat.logstashPort | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - SYS_ADMIN
        resources:
          {{- toYaml .Values.filebeat.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ include "elk-stack-platform.fullname" . }}-filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
{{- end }}