{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-filebeat
  namespace: monitoring
  labels:
    app: filebeat
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-filebeat
  labels:
    app: filebeat
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-filebeat
  labels:
    app: filebeat
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "elk-stack-platform.fullname" . }}-filebeat
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: {{ include "elk-stack-platform.fullname" . }}-filebeat
  apiGroup: rbac.authorization.k8s.io
{{- end }}