{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-test-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "20"
spec:
  containers:
  - name: test-ingestion
    image: curlimages/curl:8.4.0
    command:
    - sh
    - -c
    - |
      set -e
      echo "=========================================="
      echo "Testing Log Ingestion Pipeline"
      echo "=========================================="
      echo ""
      
      # Test 1: Send test log to Elasticsearch
      echo "✓ Test 1: Sending test log..."
      TEST_INDEX="test-logs-$(date +%Y.%m.%d)"
      RESPONSE=$(curl -s -X POST "http://{{ include "elk-stack-platform.fullname" . }}-elasticsearch:9200/${TEST_INDEX}/_doc" \
        -H 'Content-Type: application/json' \
        -d '{
          "@timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
          "level": "info",
          "message": "Helm test ingestion - verification log",
          "service": "helm-test",
          "host": "test-pod"
        }')
      
      if echo "$RESPONSE" | grep -q '"result":"created"'; then
        echo "  ✅ Test log ingested successfully"
      else
        echo "  ⚠️  Log ingestion response: $RESPONSE"
      fi
      echo ""
      
      # Test 2: Verify log was indexed
      echo "✓ Test 2: Verifying log was indexed..."
      sleep 2  # Give Elasticsearch time to index
      
      DOC_COUNT=$(curl -s "http://{{ include "elk-stack-platform.fullname" . }}-elasticsearch:9200/${TEST_INDEX}/_count" | grep -o '"count":[0-9]*' | cut -d':' -f2)
      echo "  Documents in test index: $DOC_COUNT"
      
      if [ "$DOC_COUNT" -gt 0 ]; then
        echo "  ✅ Log was successfully indexed"
      else
        echo "  ⚠️  Log may not be indexed yet"
      fi
      echo ""
      
      # Test 3: Cleanup test index
      echo "✓ Test 3: Cleaning up test index..."
      curl -s -X DELETE "http://{{ include "elk-stack-platform.fullname" . }}-elasticsearch:9200/${TEST_INDEX}" > /dev/null
      echo "  ✅ Test index cleaned up"
      echo ""
      
      echo "=========================================="
      echo "✅ Log ingestion tests passed!"
      echo "=========================================="
  restartPolicy: Never
{{- end }}
