{{- if and .Values.elasticsearch.enabled .Values.elasticsearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elk-stack-platform.fullname" . }}-elasticsearch-pvc
  namespace: monitoring
  labels:
    app: elasticsearch
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.elasticsearch.persistence.accessMode }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
{{- end }}