{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    app: elasticsearch
    {{- include "elk-stack-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
  - port: 9200
    targetPort: 9200
    name: rest
  - port: 9300
    targetPort: 9300
    name: inter-node
  selector:
    app: elasticsearch
    {{- include "elk-stack-platform.selectorLabels" . | nindent 4 }}
{{- end }}