---
- name: AWX Cloudflare Sync Resource Automation
  hosts: localhost
  gather_facts: no
  vars:
    awx_host: "http://localhost:8043"  # Update with your AWX URL
    awx_username: "admin"
    awx_password: "your_admin_password"  # Update with your AWX admin password
    cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
    project_git_url: "https://your.git.repo/with/sync-playbook.git"  # Update with your repo
    sync_playbook_name: "sync-cloudflare-domains.yml"
  tasks:
    - name: Create AWX Project
      awx.awx.project:
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        name: "Cloudflare Sync Project"
        scm_type: git
        scm_url: "{{ project_git_url }}"
        scm_branch: main
        state: present
      register: project_result

    - name: Create AWX Credential (Cloudflare API Token)
      awx.awx.credential:
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        name: "Cloudflare API Token"
        credential_type: "Machine"
        inputs:
          username: "api"
          password: "{{ cloudflare_api_token }}"
        state: present
      register: credential_result

    - name: Create AWX Job Template for Sync
      awx.awx.job_template:
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        name: "Cloudflare Sync Job"
        project: "Cloudflare Sync Project"
        playbook: "{{ sync_playbook_name }}"
        inventory: "Demo Inventory"  # Update as needed
        credentials:
          - "Cloudflare API Token"
        job_type: run
        state: present
      register: job_template_result

    - name: Create AWX Schedule for Sync Job
      awx.awx.schedule:
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        name: "Cloudflare Sync Schedule"
        unified_job_template: "Cloudflare Sync Job"
        rrule: "DTSTART;TZID=UTC:20251020T000000 RRULE:FREQ=HOURLY;INTERVAL=1"
        state: present
      register: schedule_result
