---
- name: Update AWX Job Template Survey
  hosts: localhost
  gather_facts: false
  vars:
    awx_host: "http://127.0.0.1:8052"
    awx_token: "e5VRSZHAwWshxPYbKjc5p3I0zmc1T9"
    job_template_id: 22
  survey_spec: "{{ lookup('file', playbook_dir + '/awx-survey-spec.yml') | from_yaml }}"
  tasks:
    - name: Update survey spec for job template
      uri:
        url: "{{ awx_host }}/api/v2/job_templates/{{ job_template_id }}/survey_spec/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_token }}"
          Content-Type: "application/json"
        body: "{{ survey_spec | to_json }}"
        body_format: json
        status_code: [200, 201]
      register: result

    - name: Show result
      debug:
        var: result.json
