{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  namespace: backend
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.orderService.application.database.password | quote }}
{{- end }}
