{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.fullname" . }}
  namespace: backend
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
  - port: {{ .Values.orderService.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.orderService.application.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "order-service.selectorLabels" . | nindent 4 }}
{{- end }}
